import type { Metadata } from "next";
import {Outfit , Inter} from "next/font/google"
import "./globals.css";

import Navbar from "@/components/Navbar";

const outfit = Outfit({
  subsets:['latin'],
  variable:"--font-outfit"
})

const inter = Inter({
  subsets:['latin'],
  variable:"--font-inter"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${outfit.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
